name: Action Workflow
on: 
  push:
    branches:
      - master
      - 'feature/*'
      - 'feature/**'
      - '!feature/featc'
    #branches-ignore:
    #  - null
    tags:
      - v1.*
    #tags-ignore:
    #  - null    
    paths:
      - '**.js'
      - '!filename.js'
    #paths-ignore:
    #  - 'docs/**'

  #repository_dispatch: 
  #  types: [build]
  #schedule:
  #  - cron: "0/5 * * * *"
  #  - cron: "0/6 * * * *"
  #push:
  pull_request: 
    types: [closed, assigned, opened, reopened]
jobs:
  run-github-actions: 
   runs-on: ubuntu-latest
   steps:
     - name: List Files
       run:  |
         pwd
         ls -a
         echo $GITHUB_SHA
         echo $GITHUB_REPOSITORY
         echo $GITHUB_WORKSPACE
         echo "${{ github.token }}"
         # git clone git@github:$GITHUB_WORKSPACE
         # git checkout $GITHUB_SHA
     - name: Checkout
       uses: actions/checkout@v1
     - name: List Files After Checkout
       run:  |
         pwd
         ls -a    
     - name: Simple JS Action
       id: greet
       uses:  actions/hello-world-javascript-action@v1
       with:
         who-to-greet: Pratap
     - name: Log Greeting Time
       run: echo "${{ steps.greet.outputs.time }}"

  




