name: Action Workflow
on: [push]

jobs:
  run-github-actions: 
   runs-on: ubuntu-latest
   steps:
     - name: Simple JS Action
       id: greet
       uses:  actions/hello-world-javascritp-action@v1
       with:
         who-to-greet: Pratap
     - name: Log Greeting Time
       run: echo "${{ steps.greet.outputs.time }}"

  




